### PR TITLE
Added support for Pcap options

### PR DESCRIPTION
**Pull request by J-Gras**
This patch adds support for AF_PACKET's fanout load balancing (introduced in bro/bro#40) to BroControl. Additionally it allows to configure the other Pcap options using broctl.cfg. In total the following new options have been intoduced:
* PcapSnaplen
* PcapBufsize
* PacketFanoutID
* PacketFanoutDefrag

### CODE REVIEW

**Comment by sethhall** [comment]
Unfortunately, it was discovered that the method for doing load balancing with AF_Packet through libpcap does not work correctly.  

More information can be found here: https://bro-tracker.atlassian.net/browse/BIT-1363

**Comment by sethhall** [comment]
Ugh, nevermind.  You knew all of this already.

**Comment by J-Gras** [comment]
As the original commit to Bro has been replaced by AF_Packet packet source plugin (bro/bro-plugins#9), I will close this one. To have basic support for packet source plugins I added a new load balancing method (bro/broctl#2). If you want to keep the Pcap options not connected to packet fanout, let me know.

**Comment by J-Gras** [comment]
I just read in the [ticket] (https://bro-tracker.atlassian.net/browse/BIT-1363) that @michalpurzynski would like to keep Bufsize and Snaplen options, so I removed just the fanout related stuff and reopened.

**Pull request merged**
